# Generated by Django 5.2.3 on 2025-07-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_husband_alter_tagpost_slug_women_husband'),
    ]

    operations = [
        migrations.AddField(
            model_name='husband',
            name='m_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
